#!/bin/bash
#
# Copyright (c) 2019-2020 Roku, Inc. All rights reserved.
#
# References:
# https://github.com/image-media-playlist/spec/blob/master/image_media_playlist_v0_4.pdf
# https://gist.github.com/vvo/6000388


if [ $# -lt 5 ]; then
    echo "Usage: $0 <input-prefix> <resolution> <cols> <rows> <duration>"
    exit 1
fi

INPREFIX=$1
RESOLUTION=$2
COLS=$3
ROWS=$4
TARGETDURATION=$5
OUTPREFIX=$RESOLUTION
OUTFILE=$OUTPREFIX-${COLS}x${ROWS}.m3u8

# All parameters need to be specified
# The $INPREFIX parameter is a directory containing the thumbnails
# The $RESOLUTION parameter is a name without count string, .e.g. 320x180
# The $COLS parameter is tile horizontal count, e.g. 5
# The $ROWS parameter is tile vertical count, e.g. 4
# The $TARGETDURATION parameter is the value set in EXT-X-TARGETDURATION, EXTINF, etc
#
# One example of running this command:
# $ ./scripts/gen_playlist.sh /tmp/thumb-tile-5x4- 320x180 5 4 10

# The script takes the tiles and generates the HLS playlist
# Usually, this script uses input tiles generated by gen_tiles.sh

cat <<EOT >> $OUTFILE
#EXTM3U
#EXT-X-TARGETDURATION:$TARGETDURATION
#EXT-X-VERSION:7
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-IMAGES-ONLY

EOT

let "TILEDURATION=$TARGETDURATION * $COLS * $ROWS"
echo "TILEDURATION = $TILEDURATION"

let "TILECOUNT=`ls -l $INPREFIX* |wc -l`"
echo "TILECOUNT = $TILECOUNT"

TILE=1

while [ $TILE -le $TILECOUNT ]
do
	echo "#EXTINF:$TILEDURATION.000," >> $OUTFILE
	echo "#EXT-X-TILES:RESOLUTION=${RESOLUTION},LAYOUT=${COLS}x${ROWS},DURATION=${TARGETDURATION}.000" >> $OUTFILE
	echo "${INPREFIX}-${COLS}x${ROWS}-${TILE}.jpg" >> $OUTFILE
	let "TILE= $TILE + 1"
done

echo >> $OUTFILE
echo "#EXT-X-ENDLIST" >> $OUTFILE
